services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: duxmax-postgres
    environment:
      POSTGRES_DB: duxmax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - duxmax-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: duxmax-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - duxmax-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duxmax-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/duxmax
      - REDIS_URL=redis://redis:6379
      - BETTER_AUTH_SECRET=your-production-secret
      - BETTER_AUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - duxmax-network
    volumes:
      - ./uploads:/app/uploads

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: duxmax-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@duxmax.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - duxmax-network
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:

networks:
  duxmax-network:
    driver: bridge
